### ISSUE TITLE
[FEAT] Add `glimpse()`

### ISSUE THREAD

**Issue by thomas-neitmann** [nathaneastwood/poorman#40]
I tried rerunning the code of my [recent blog post](https://thomasadventure.blog/posts/calculating-change-from-baseline-in-r/) using `{poorman}` upon a request in the comments. Everything worked, except `glimpse()`. Do you plan on adding this function?

**Comment by nathaneastwood** [comment]
Oh wow I completely forgot this function even existed! I'll see what I can do :)

**Comment by thomas-neitmann** [comment]
Wow, that was fast. Thanks a lot!

**Comment by nathaneastwood** [comment]
Not sure I’m entirely happy with it. It’s quite simply a wrapper around `str` which is actually what `glimpse.default` does anyway. The `{tidyverse}` devs do some fancy stuff for `data.frame`s but I’m a poor man and I don’t have access to that stuff. That being said, `str` actually adds a dependency on `{utils}` which I’m not happy about since I believe there are some OSes which don’t ship with all R “base” packages; you literally just get `{base}`. Therefore I may look to add my own version of `str` at some postnl, we’ll see.

**Comment by jangorecki** [comment]
It is safe to assume `utils` is available on any non-artificial configuration of R. `install.packages` comes from `utils`.

**Comment by nathaneastwood** [comment]
Thanks for the clarification @jangorecki. 

It might be nice in the future to make an attempt at writing a nicer version of `glimpse()` specifically for `{poorman}` similar to the new `{terse}` package by @coolbutuseless.
