### ISSUE TITLE
Rich man is coming to visit

### ISSUE THREAD

**Issue by hope-data-science** [nathaneastwood/poorman#7]
I bump into this package today and admire all the spirit and contribution you made into this work. I have made two packages myself  using data.table (I am not alone of course), and I find these experience extremly interesting and valuable. FYI: <https://github.com/hope-data-science/tidyfst> and <https://github.com/hope-data-science/tidyft>.

Here comes two questions: (1) Are these APIs 100% the same as dplyr? I tried but failed (well no failed sometimes, I think other ways might be more efficient so I decided to use my own style in some functions, what is it like in poorman); (2) Any test on performance? Base R is considered to be very efficient, is poorman acts even better than dplyr in some operations?

Thanks.

**Comment by nathaneastwood** [comment]
Hey, thanks for your questions. I checked out your packages and they seem pretty neat. I have made the API 100% the same, yes. There may be some instances where things aren't quite the same yet but that is because I have not finished writing the package yet.

As for performance, I have not performed any detailed benchmarks, yet. I actually probably won't be doing for the foreseeable future since there are plenty of benchmarks out there comparing `dplyr` and `base`. Since `poorman` is just a wrapper around `base`, I suspect `poorman`'s performance will be similar (maybe with some slight overhead) to `base`.
